env: local
output_dir: ../outputs/data_icd10
tokenized_dir_name: "tokenized"
paths:
  run_name: "icd10_small"
loader:
  data_dir:  ../data/formatted/synthea500_icd10 #../outputs/data_icd10
  patients_info: patients_info.csv
  concepts: [
    diagnose
  ]
  batch_size: 64
  chunksize: 300

features:
  age: 
    round: 
      decimal: 2
  abspos:
    year: 2020
    month: 1
    day: 26
  segment: true
  background: ['GENDER']

tokenizer:
  sep_tokens: true
  cls_token: true
  padding: false
  truncation: null
  #cutoffs:
   # D: 3 # diagnosis
    #M: 4 # medication

excluder:
  min_len: 2

split_ratios:
  pretrain: 0.72 # 80% of 90%
  finetune: 0.18 # 20% of 90%
  test: 0.1
n_splits: 2 # used when splitting in cv fashion
handler:
  concept_fill: "[UNK]"    
  num_fill: -100
  drop: true

exclude_pids: outputs/pretraining/behrt_test/finetune_TEST_OUTCOME_censored_4_days_post_TEST_OUTCOME_test/val_pids.pt
assigned_pids:
  pretrain: 
   - outputs/pretraining/behrt_test/finetune_TEST_OUTCOME_censored_4_days_post_TEST_OUTCOME_test/train_pids.pt
   - outputs/pretraining/behrt_test/finetune_TEST_OUTCOME_censored_4_days_post_TEST_OUTCOME_test/val_pids.pt
   

