env: local
# output_dir: "../outputs/data_icd10_l"
output_dir: "C:\\Users\\14552\\Desktop\\block_5\\test_run"
run_name: "icd10"
loader:
  # data_dir: ../data/formatted/synthea500_icd10
  data_dir: "C:\\Users\\14552\\Desktop\\block_5\\test_run"
  patients_info: patients_info.csv
  concepts: [
    # diagnose
    medication
  ]
  batch_size: 50
  chunksize: 300

features:
  age: true
  abspos:
    year: 2020
    month: 1
    day: 26
  segment: true
  background: ['GENDER']

  # medicine: true # concept is medicine
  # dose: true
  # unit: true
  # dose: false
  # unit: false

tokenizer:
  sep_tokens: true
  cls_token: true
  padding: false
  truncation: 128
  max_concept_length: false

excluder:
  min_len: 2

split_ratios:
  train: 0.5
  val: 0.4
  test: 0.1

handler:
  concept_fill: "[UNK]"    
  num_fill: -100
  drop: true
