env: local
output_dir: ../outputs/data_icd10
run_name: "icd10"
loader:
  data_dir: ../data/formatted/synthea500_icd10 
  patients_info: patients_info.csv
  concepts: [
    diagnose
  ]
  batch_size: 50
  chunksize: 300

features:
  age: true
  abspos:
    year: 2020
    month: 1
    day: 26
  segment: true
  background: ['GENDER']

tokenizer:
  sep_tokens: true
  cls_token: true
  padding: false
  truncation: 128
  max_concept_length: false

excluder:
  min_len: 2

split_ratios:
  train: 0.8
  val: 0.1
  test: 0.1

handler:
  concept_fill: "[UNK]"    
  num_fill: -100
  drop: true
