env: local
run_name: test
loader:
  data_dir: ../outputs/data_icd10
  model_dir: outputs/pretraining/test
  checkpoint_num: 19
output_dir: outputs/embeddings/test/
embeddings:
  stop_iter: 100
  batch_size: 128
dims: [50]
project: true
project_methods: 
  umap:
    _target_: UMAP