env: local
paths:
  data_path: "../outputs/data_icd10_l"
  model_path: "outputs/pretraining/test"
  outcomes_path: "../outputs/outcomes/TEST.pt"
  checkpoint_epoch: 2
  run_name: "test2"

train_data:
  num_patients: null
val_data:
  num_patients: null

outcomes: 
  outcome1:
    type: TEST_OUTCOME
    n_hours: 12 # censor time
    censor_type: TEST_OUTCOME
  outcome2:
    type: TEST_OUTCOME
    n_hours: 24 # censor time
    censor_type: TEST_OUTCOME


forwarder_args:
  batch_size: 64
  pooler:
    _target_: evaluation.poolings.MeanPooling
  
    
 
