env: local
paths:
  data_path: "../outputs/data_icd10_l"
  model_path: "outputs/pretraining/test"
  outcomes_path: "../outputs/outcomes/TEST.pt"
  checkpoint_epoch: 2
  output_path: "outputs/finetuning"
  run_name: "test"

train_data:
  num_patients: 400
val_data:
  num_patients: 80

outcome: 
  type: TEST_OUTCOME
  n_hours: 12 # censor time
  censor_type: TEST_OUTCOME

forwarder_args:
  batch_size: 64
  pooler:
    _target_: evaluation.poolings.MeanPooling
  output_path: "outputs/pretraining/test/encodings/censored_patients/censored_patients.hdf5"
    
 
