env: local
paths:
  data_path: "../outputs/data_icd10_l"
  model_path: "outputs/pretraining/test/checkpoints"
  checkpoint_epoch: 2
  outcome: "TEST.pt"
  censor: "TEST.pt"
  output_path: "outputs/finetuning"
  run_name: "finetune"

train_data:
  num_patients: 400
val_data:
  num_patients: 80

outcome: 
  type: TEST_OUTCOME
  n_hours: 12 # censor time
  censor_type: TEST_OUTCOME

forwarder_args:
  batch_size: 64
  info: true
  
 
