env: local
run_name: AE_0
model_dir: "outputs/pretraining/test"
n_folds:
  2
tasks:
  first:
    folder: TEST_OUTCOME_Patients_0k_Censor_3hours_post_TEST_OUTCOME
sampler:
  n_samples: 500
uncensored: Patients_0k_Uncensored
metrics:
  roc_auc_score:
    _target_: sklearn.metrics.roc_auc_score
  pr_auc_score:
    _target_: sklearn.metrics.average_precision_score
  accuracy_score:
    _target_: sklearn.metrics.accuracy_score
  precision_score:
    _target_: sklearn.metrics.precision_score
  recall_score:
    _target_: sklearn.metrics.recall_score
  f1_score:
    _target_: sklearn.metrics.f1_score
  specificity_score:
    _target_: evaluation.metrics.specificity

parallel:
  n_jobs: 4
  temp_folder: "outputs/tmp"


optimizer:
  param_grid:
    n_estimators: [100]
    max_depth: [2, 5]
    min_samples_split: [2,3]
  split: 0.7
