env: local
paths:
  finetune_features_path: "outputs/pretraining/behrt_plus_test/finetune_TEST_OUTCOME_censored_20_hours_post_TEST_OUTCOME_test"
  run_name: "test"

model:
  _target_: sklearn.ensemble.RandomForestClassifier

trainer_args:
  sampler: true
  pos_weight: null

metrics:
  roc_auc_score:
    _target_: sklearn.metrics.roc_auc_score
  pr_auc_score:
    _target_: sklearn.metrics.average_precision_score
  accuracy_score:
    _target_: sklearn.metrics.accuracy_score
  precision_score:
    _target_: sklearn.metrics.precision_score
  recall_score:
    _target_: sklearn.metrics.recall_score
  f1_score:
    _target_: sklearn.metrics.f1_score
  specificity_score:
    _target_: evaluation.metrics.specificity
  
  
 
