env: local
run_name: AE_0
model_dir: "outputs/pretraining/test"
n_folds:
  2
tasks:
  first:
    folder: TEST_OUTCOME_Patients_0k_Censor_3hours_post_TEST_OUTCOME
    oversampling_ratio: .3
sampler:
  n_samples: 100
uncensored: Patients_0k_Uncensored
metrics:
  roc_auc_score:
    _target_: sklearn.metrics.roc_auc_score
  pr_auc_score:
    _target_: sklearn.metrics.average_precision_score
  accuracy_score:
    _target_: sklearn.metrics.accuracy_score
  precision_score:
    _target_: sklearn.metrics.precision_score
  recall_score:
    _target_: sklearn.metrics.recall_score
param_grid:
  n_estimators: [100]
  max_depth: [5]
  min_samples_split: [2]