env: local
paths:
  data_path: "../outputs/data_icd10"
  model_path: "outputs/pretraining/behrt_plus_test"
  checkpoint_epoch: 2
  outcome: "outcomes/TEST.pt"
  censor: "outcomes/TEST.pt"
  #output_path: "outputs/finetuning"
  run_name: "test"
  # tokenized_dir: "tokenized"

model:
  pool_type: "mean"

data:
  num_train_patients: 150
  num_val_patients: 20
  truncation_len: 20

outcome: 
  type: TEST_OUTCOME
  n_hours: 12 # censor time
  censor_type: TEST_OUTCOME

trainer_args:
  sampler: null
  pos_weight: null
  batch_size: 8
  effective_batch_size: 16
  epochs: 2
  info: true
  gradient_clip: 
    clip_value: 1.0
  mixed_precision: false

optimizer:
  lr: 5e-4
  eps: 1e-6

scheduler:
  num_warmup_steps: 10
  num_training_steps: 100

metrics:
  accuracy:
    _target_: evaluation.metrics.Accuracy
  precision:
    _target_: evaluation.metrics.Precision
  recall:
    _target_: evaluation.metrics.Recall
  roc_auc:
    _target_: evaluation.metrics.ROC_AUC
  
 
