env: local
paths:
  # data_path: 'pretrain_datasets/diagnosis_medication/070623/outputs/data' # inside mounted datastore
  data_path: "..\\outputs\\data_icd10" # C:\Users\fjn197\PhD\projects\PHAIR\pipelines\ehr2vec-azure-std\ehr2vec\outputs\data_icd10 # inside mounted datastore
  output_path: "outputs/h_pretraining"
  run_name: test
  
dataset:
  masked_ratio: 0.15
  ignore_special_tokens: true

train_data:  
  num_patients: 100
val_data:
  num_patients: 20

trainer_args:
  batch_size: 64
  effective_batch_size: 128
  epochs: 3
  info: true
  sampler: null

model:
  max_position_embeddings: 512
  linear: true
  hidden_size: 96
  num_hidden_layers: 3
  num_attention_heads: 3
  intermediate_size: 64
  type_vocab_size: 1000 
  pool_type: mean

optimizer:
  lr: 5e-4
  weight_decay: 0
  epsilon: 1e-6

scheduler:
  num_warmup_steps: 1
  num_training_steps: 10
metrics:
  null