env: local
outcomes_name: "AE_0"
features_dir: ../outputs/data_icd10
loader:
  data_dir: ../data/formatted/synthea500_icd10 
  concepts: [
    diagnose
  ]
  batch_size: 50
  chunksize: 300
outcomes:
  MAJOR_BLEEDING: 
    type: [CONCEPT]
    match: [[DD62, DI60, DI61, DI62, DI690, DI691, DJ942, DK250, DK252, DK254, DK256, DK260, DK262, DK264, DK276, DK270, DK272, DK274, DK276, DK280, DK282, DK284, DK286, DK290, DK298A, DK625, DK638C, DK920, DK921, DK922, DN02, DN93, DR04, DR31, DS064, DS065, DS066]]
  STEVEN_JOHNSON:
     type: [CONCEPT]
     match: [[DL511, DL512]]
  CANCER_COLON:
    type: [CONCEPT]
    match: [[DC18]]
  OSTEONECROSIS:
    type: [CONCEPT]
    match: [[DM87]]
  DIARRHEA:
    type: [CONCEPT]
    match: [[DK529, DK521, MA07D]]
  PAIN:
    type: [CONCEPT]
    match: [[MN02A, MN02B, MM02A]]
  SLEEP_DISORDER:
    type: [CONCEPT]
    match: [[DF51, DDG47, MN05CF, MN05CH]]
  VACCINATION_GRANULOMA:
    type: [CONCEPT]
    match: [[DT881B]]
  BASAL_CELL_CARCINOMA:
    type: [CONCEPT]
    match: [[DC44]]



  