env: azure
run_name: prepare_PREGNANCY_data
outcomes_name: "PREGNANCY"
features_dir: features/diagnosis_medication/01082023/outputs/data
loader:
  data_dir: formatted_data/diagnosis_medication_full_250623/outputs
  concepts: [
    diagnosis,
  ]
  batch_size: 50000
  chunksize: 20000000
  test: false
outcomes:
  PREGNANCY: 
    type: [CONCEPT]
    match: [[DZ340, DZ348, DZ349]]
  PREGNANCY_COMPLICATIONS:
    type: [CONCEPT]
    match: [[DO365, DO365A, DO366, DO409, DO410]]
  WEIGHT_INSUFFICIENCY:
    type: [CONCEPT]
    match: [[DO365]]
  PLACENTA_INSUFFICIENCY:
    type: [CONCEPT]
    match: [[DO365A]]
  LARGE_FETUS:
    type: [CONCEPT]
    match: [[DO366]]
  HYDRAMNION:
    type: [CONCEPT]
    match: [[DO409]]
  OLIGOHYDRAMNION:
    type: [CONCEPT]
    match: [[DO410]]
