env: azure
paths:
  run_name: RCTS_TREATMENTS_test
outcomes_name: RCTS_TREATMENTS
features_dir: features/med
loader:
  data_dir: formatted_data/med_name
  patients_info: patients_info.parquet
  concepts: [
    medication,
  ]
  batch_size: 20000 # 200000
  chunksize: 20000000
  test: true
outcomes:
  LIRAGLUTIDE:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[liraglutid]]

  DAPAGLIFLOZIN_EMPAGLIFLOZIN:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[dapagliflozin, empagliflozin]]

  CANAGLIFLOZIN:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[canagliflozin]]

  LINAGLIPTIN:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[linagliptin]]

  SITAGLIPTIN:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[sitagliptin]]

  SAXAGLIPTIN:
    match_how: contains 
    case_sensitive: false
    type: [CONCEPT]
    match: [[saxagliptin]]

  METFORMIN:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[metformin]]
  
  PRASUGREL:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[prasugrel]]

  TICAGRELOR:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[ticagrelor]]

  APIXABAN:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[apixaban]]

  #DABIGATRAN: # we have only
   # match_how: contains
    #case_sensitive: false
    #type: [CONCEPT]
    #match: [[dabigatran]]

  RIVAROXABAN:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[rivaroxaban]]

  TELMISARTAN:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[telmisartan]]

  ZOLEDRONIC_ACID:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[zoledronsyre]]

  TERIPARATIDE:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[teriparatid]]

  DAPAGLIFLOZIN: 
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[dapagliflozin]]

  SACUBITRIL_VALSARTAN:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[Valsartan og sacubitril]]
  VALSARTAN:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[valsartan]]
  SACUBITRIL:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[sacubitril]]

  MOMETASONE_FUROATE_FORMOTEROL: # not sure if this is correct
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[mometason, formoterol]]
  MOMETASONE:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[mometason]]
  FORMOTEROL:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[formoterol]]
    
  BUDESONIDE_FORMOTEROL:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [['Formoterol og budesonid', 'Formoterol og budesonid']]
  BUDESONIDE:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[budesonid]]

  FLUTICASONE_UMECLIDINIUM_VILANTEROL:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[ 'Vilanterol, umeclidiniumbromid og fluticasonfuroat']]

  UMECLIDINIUM:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[umeclidiniumbromid]]
  
  VILANTEROL:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[vilanterol]]

  TIOTROPIUM:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[tiotropium]]

  # ADVAIR: # not in data
  #   match_how: contains
  #   case_sensitive: false
  #   type: [CONCEPT]
  #   match: [[advair]]

  DEGARELIX:
    match_how: contains
    case_sensitive: false
    type: [CONCEPT]
    match: [[degarelix]]

    
  