env: local
outcomes_name: "TEST_CENSOR"
features_dir: ../outputs/data_icd10
loader:
  data_dir: ../data/formatted/synthea500_icd10 
  patients_info: patients_info.csv
  concepts: [
    diagnose
  ]
  batch_size: 50
  chunksize: 300
outcomes:
  TEST_OUTCOME: 
    type: [CONCEPT]
    match: [['DJ329', 'DN186']]
  TEST_CENSOR:
    type: [CONCEPT]
    match: [['DJ0190']]