env: local
paths:
  # data_path: 'pretrain_datasets/diagnosis_medication/070623/outputs/data' # inside mounted datastore
  data_path: "..\\outputs\\data_icd10"
  output_path: 'outputs/pretraining'
  type: med_diag
  run_name: behrt_test
  tokenized_dir: tokenized
  model_path: outputs/pretraining/behrt_test
  
data:
  dataset:
    masked_ratio: 0.15
    ignore_special_tokens: true
  truncation_len: 20
  num_train_patients: 100
  num_val_patients: 20
  remove_background: true
  min_len: 2

trainer_args:
  batch_size: 8
  effective_batch_size: 16
  epochs: 10
  info: true
  gradient_clip: 
    clip_value: 1.0
  mixed_precision: false
  shuffle: true
  early_stopping: null # num_epochs or null/false

metrics:
  top1:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 1
  top10:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 10
