output_dir: "output/data"
loader:
  data_dir: C:\Users\fjn197\PhD\projects\PHAIR\pipelines\ehr_preprocess\formatted_data\synthea500
  patients_info: patients_info.csv
  concepts: [
    diagnose,
    medication
  ]
  batch_size: 50
  chunksize: 300

features:
  age: true
  abspos:
    year: 2020
    month: 1
    day: 26
  segment: true
  background: ['GENDER', 'ETHNICITY', 'RACE']

tokenizer:
  sep_tokens: true
  cls_token: true
  padding: false
  truncation: 128
  max_concept_length: false

dataset:
  masked_ratio: 0.15
  ignore_special_tokens: true

excluder:
  min_len: 2

split_ratios:
  train: 0.5
  val: 0.4
  test: 0.1

handler:
  concept_fill: "[UNK]"    
  num_fill: -100
  drop: true
