loader:
  data_dir: formatted_data
  patients_info: patients_info.csv
  concepts: [
    diagnose,
    medication,
    custom_events
  ]

features: 
  age: true
  abspos:
    year: 2020
    month: 1
    day: 26
  segment: true
  background: ['GENDER']

outcomes:
  HOSPITAL_ADMISSION: true
  ICU_ADMISSION: true
  MECHANICAL_VENTILATION: true
  DEATH: true

tokenizer:
  sep_tokens: true
  cls_token: true
  padding: false
  truncation: 512

mlm:
  ignore_special_tokens: true
