data_dir: formatted_data
concepts: [
  diagnose,
  medication
]
patients_info: patients_info.csv

features: 
  age: true
  abspos:
    year: 2020
    month: 1
    day: 26
  segment: true
  background: ['GENDER']
