train_encoded: 'train_encoded.pt'
train_outcomes: 'train_outcomes.pt'
val_encoded: 'val_encoded.pt'
val_outcomes: 'val_outcomes.pt'
vocabulary: 'vocabulary.pt'

outcome: 
  type: HOSPITAL_ADMISSION
  n_hours: 12
  censor_type: HOSPITAL_ADMISSION

model:
  max_position_embeddings: 512
  linear: true
  hidden_size: 192
  num_hidden_layers: 6
  num_attention_heads: 6
  intermediate_size: 64
  pool_type: cls

optimizer:
  lr: 5e-5
  weight_decay: 0
  epsilon: 1e-6

trainer_args:
  batch_size: 32
  effective_batch_size: 512
  epochs: 10
  info: true

metrics:
  accuracy:
    _target_: evaluation.metrics.binary_hit
    _partial_: true
