env: local

paths:
  # data_path: 'pretrain_datasets/diagnosis_medication/070623/outputs/data' # inside mounted datastore
  data_path: C:\Users\fjn197\PhD\projects\PHAIR\pipelines\ehr2vec-azure-std\ehr2vec\outputs\data_icd10 
  output_path: 'pretraining'
  run_name: behrt_base_diag_scheduler
  
dataset:
  masked_ratio: 0.15
  ignore_special_tokens: true
  num_patients: 100000

trainer_args:
  batch_size: 32
  effective_batch_size: 128
  epochs: 10
  info: true
  sampler: null

model:
  max_position_embeddings: 512
  linear: true
  hidden_size: 96
  num_hidden_layers: 3
  num_attention_heads: 3
  intermediate_size: 64
  type_vocab_size: 1000
  pool_type: mean

optimizer:
  lr: 5e-4
  weight_decay: 0
  epsilon: 1e-6

scheduler:
  num_warmup_steps: 10
  num_training_steps: 100

metrics:
  top1:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 1
  top10:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 10
  top100:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 100
