paths:
  data_path: 'output/data'
  run_name: test
  
dataset:
  masked_ratio: 0.15
  ignore_special_tokens: true

trainer_args:
  batch_size: 256
  effective_batch_size: 256
  epochs: 3
  info: true
  sampler: null

model:
  max_position_embeddings: 512
  linear: true
  hidden_size: 96
  num_hidden_layers: 3
  num_attention_heads: 3
  intermediate_size: 64
  type_vocab_size: 1000
  pool_type: mean

optimizer:
  lr: 5e-4
  weight_decay: 0
  epsilon: 1e-6

metrics:
  top1:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 1
  top10:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 10
  top100:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 100
