train_dataset: data\tokenized\hierarchical\test\dataset.test
val_dataset: data\tokenized\hierarchical\test\dataset.val

model:
  max_position_embeddings: 512
  linear: true
  hidden_size: 192
  num_hidden_layers: 6
  num_attention_heads: 6
  intermediate_size: 64

optimizer:
  lr: 5e-5
  weight_decay: 0
  epsilon: 1e-6

trainer_args:
  batch_size: 5 #32
  effective_batch_size: 10 #512
  epochs: 3
  info: true

